---
title: "Meteorites"
author: "Carsten Stann"
date: "6/11/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Tidy tuesday: Meteorites - week 06-11-2019 

library(tidyverse)
library(skimr)
library(maps)
library(revgeo)
library(purrr)
```
Import & glimpse data
```{r}
meteor_import <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-06-11/meteorites.csv")

glimpse(meteor_import)
meteor_import
skim(meteor_import)
summary(meteor_import)
```

```{r}
meteor <- meteor_import %>%
   drop_na(long, lat) %>%
   filter(between(long, -200, 200) & lat >= -85.1 & between(year, 1600, 2019)) %>%
   mutate(n = row_number())

```

Reverse geocode long/lat points to obtain location information
```{r}
geocodes_1_1000 <- revgeo(longitude = meteor$long[1:1000], 
       latitude = meteor$lat[1:1000], 
       provider = "google",
       API = "AIzaSyAwAcy7ryigDwst3LYve30cAklL4caAEZg",
       output = "frame")
```


```{r}
ggplot(meteor, aes(mass)) +
   geom_histogram() +
   scale_x_log10()

meteor %>% filter(year >= 1900 & year != 2101) %>% 
ggplot(aes(year)) +
   geom_histogram(binwidth = 1)

```


Plot on world map
```{r}
library(gganimate)
world <- map_data("world")

world %>% arrange(desc(lat))

meteor.plot <- filter(meteor, between(long, -200, 200) & lat >= -85.1 & between(year, 1600, 2019))

ggplot(world) +
   geom_polygon(aes(x = long, y = lat, group = group)) +
   geom_point(data = meteor.plot, aes(x = long, y = lat), size = 0.1, alpha = 0.5, color = "red") +
   ylim(c(-84.9, 83.59961)) +
   theme_minimal() +
   labs(title = "Known Meteorite Landings since 1600", 
        y = "Latitude",
        x = "Longitute",
        caption = "Data: NASA Open Data Portal")


states <- map_data("state")
states.data <- filter(meteor.plot, between(long, -124.68, -67.01) & between(lat, 25.13, 49.38))

ggplot(states) +
   geom_polygon(aes(x = long, y = lat, group = group)) +
   geom_point(data = states.data, aes(x = long, y = lat), size = 0.5, alpha = 0.5, color = "red")

summary(states)


```

```{r}



```{r}
meteor %>% arrange(year) %>% View()
```

