# custom theme --------------------------------------------------------------------------
# based on NASA Design: https://nasa.github.io/nasawds-site/components/colors/

library(ggplot2)

theme_nasa <- theme(
   line = element_line(colour = "#d6d7d9", 
                       size = 0.4, 
                       linetype = 1, 
                       lineend = "butt"),
   rect = element_rect(fill = "#323a45", 
                       color = "white", 
                       size = 0.4, 
                       linetype = 1),
   text = element_text(family = "Source Sans Pro Semibold", 
                       face = "plain", 
                       color = "white", 
                       size = 10, 
                       lineheight = 0.9, 
                       hjust = 0.5, 
                       vjust = 0.5, 
                       angle = 0, 
                       margin = margin(),  
                       debug = FALSE),
   axis.line = element_line(color = "#d6d7d9", 
                            size = 0.4),
   axis.text = element_text(size = 10, 
                            color = "white"),
   axis.text.x = element_text(margin = margin(t = 3), 
                              vjust = 1), 
   axis.text.x.top = element_text(margin = margin(b = 3), 
                                  vjust = 0), 
   axis.text.y = element_text(margin = margin(r = 3), 
                              hjust = 1), 
   axis.text.y.right = element_text(margin = margin(l = 3), 
                                    hjust = 0), 
   axis.ticks = element_line(color = "white", 
                             size = 0.3),
   axis.ticks.length = unit(6, "pt"), 
   axis.title = element_text(size = 12, 
                             face = "bold"),
   axis.title.x = element_text(margin = unit(c(3.5, 0, 0, 3.5), "mm"), 
                               vjust = 1), 
   axis.title.x.top = element_text(margin = margin(b = 6), 
                                   vjust = 0), 
   axis.title.y = element_text(angle = 90, 
                               margin = unit(c(0, 3.5, 0, 0), "mm"), 
                               vjust = 1), 
   axis.title.y.right = element_text(angle = -90, 
                                     margin = margin(l = 6), 
                                     vjust = 0), 
   legend.background = element_rect(colour = NA),
   legend.spacing = unit(0.4, "cm"), 
   legend.spacing.x = NULL, 
   legend.spacing.y = NULL, 
   legend.margin = margin(0.2, 0.2, 0.2, 0.2, "cm"), 
   legend.key = element_rect(fill = "#323a45", colour = "#323a45"),
   legend.key.size = unit(1.2, "lines"), 
   legend.key.height = NULL, 
   legend.key.width = NULL, 
   legend.text = element_text(size = 10), 
   legend.text.align = NULL, 
   legend.title = element_text(size = 12),
   legend.title.align = NULL,
   legend.position = "right", 
   legend.direction = NULL, 
   legend.justification = "center", 
   legend.box = NULL, 
   legend.box.margin = margin(0, 0, 0, 0, "cm"), 
   legend.box.background = element_blank(), 
   legend.box.spacing = unit(0.4, "cm"), 
   panel.background = element_rect(fill = NA, 
                                   color = NA), 
   panel.border = element_rect(color = NA, 
                               fill = NA),
   panel.grid = element_line(size = 0.2, 
                             linetype = 'solid',
                             colour = "#d6d7d9"),
   panel.grid.major = element_line(size = 0.1, 
                                   linetype = 'solid',
                                   colour = "#d6d7d9"),
   panel.grid.minor = element_line(size = 0.03, 
                                   linetype = 'solid',
                                   colour = "#d6d7d9"),
   panel.spacing = unit(6, "pt"),
   panel.spacing.x = NULL, 
   panel.spacing.y = NULL, 
   panel.ontop = FALSE,
   strip.background = element_rect(fill = "#d6d7d9", 
                                   color = "#d6d7d9"), 
   strip.text = element_text(colour = "white", 
                             size = 12, 
                             face = "bold"), 
   strip.text.x = element_text(margin = margin(t = 6, b = 6)), 
   strip.text.y = element_text(angle = -90, 
                               margin = margin(l = 6, r = 6)), 
   strip.placement = "inside", 
   strip.placement.x = NULL, 
   strip.placement.y = NULL, 
   strip.switch.pad.grid = unit(0.1, "cm"), 
   strip.switch.pad.wrap = unit(0.1, "cm"), 
   plot.background = element_rect(color = NA), 
   plot.title = element_text(size = 20, 
                             face = "bold",
                             hjust = 0, 
                             vjust = 1,
                             margin = margin(t = 4, b = 8)),
   plot.subtitle = element_text(size = 16,
                                hjust = 0, 
                                vjust = 1,
                                margin = margin(b = 8),
                                face = "plain"), 
   plot.caption = element_text(size = 8, 
                               color = "white",
                               margin = margin(t = 6),
                               hjust = 1, 
                               vjust = 1,
                               face = "plain"),
   plot.margin = margin(10, 10, 10, 10), 
   complete = TRUE,
   plot.tag = element_text(size = rel(1.5), 
                           face = "bold", 
                           hjust = 0.5, 
                           vjust = 0.5), 
   plot.tag.position = "topleft"
)

theme_set(theme_nasa)
